// Gradle-Plugins fuer dieses Projekt auswaehlen
plugins {
	
    // Java-Applikation bauen
    id 'application'
    // Plugin fuer JavaFX-Projekte, '0.1.0' neueste Version 
    id 'org.openjfx.javafxplugin' version '0.1.0'

    // Unit-Test-Bibliotheken
    id 'jvm-test-suite'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'de.hsrm.mi.enia.moodplayer.presentation.MoodPlayerGUI'
}

// Verwendung des FX-Plugins: FX-Version und Module wuenschen
javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

// Test-Konfiguration (./gradlew test)
testing {
    suites { 
        test { 
            useJUnitJupiter() 
        }
    }
}

// Zusaetzlich benoetigte Abhaengigkeiten
dependencies {
	implementation fileTree('libs') { include '*.jar' }
	// FÜr ID3-Tag Auslesen
	implementation 'com.mpatric:mp3agic:0.9.1'
}

// Abhaengigkeiten herunterladen von...
repositories {
    mavenCentral()
}

